// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using costnotebook_backend.Models;

#nullable disable

namespace costnotebook_backend.Migrations
{
    [DbContext(typeof(CostNotebookDbContext))]
    [Migration("20220809160230_AddNewUser")]
    partial class AddNewUser
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("costnotebook_backend.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"), 1L, 1);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserEmail")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            FirstName = "Jakub",
                            Password = "pass123",
                            UserEmail = "jakukprzybyl@gmail.com"
                        },
                        new
                        {
                            UserID = 2,
                            FirstName = "Krzysztof",
                            Password = "pass123",
                            UserEmail = "krzychudobrz@gmail.com"
                        },
                        new
                        {
                            UserID = 3,
                            FirstName = "Łukasz",
                            Password = "pass123",
                            UserEmail = "lukaszprzybyl@gmail.com"
                        },
                        new
                        {
                            UserID = 4,
                            FirstName = "Admin",
                            Password = "admin",
                            UserEmail = "admin@admin.com"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
